lvim.keys.normal_mode["<A-j>"] = ":m .+1<CR>=="
lvim.keys.normal_mode["<A-k>"] = ":m .-2<CR>=="
lvim.keys.insert_mode["<A-j>"] = ":m .+1<CR>==gi"
lvim.keys.insert_mode["<A-k>"] = ":m .-2<CR>==gi"
lvim.keys.visual_mode["<A-j>"] = ":m '>+1<CR>gv=gv"
lvim.keys.visual_mode["<A-k>"] = ":m '<-2<CR>gv=gv"
