# vim:set ft=tmux:
%hidden MODULE_NAME="continuum"

set -ogq @catppuccin_continuum_icon "󰸨 "
set -ogqF @catppuccin_continuum_color "#{E:@thm_yellow}"
set -ogq @catppuccin_continuum_text " #{continuum_status}"

source -F "#{HOME}/.local/share/tmux/plugins/tmux/utils/status_module.conf"
