# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'     # The 'error_symbol' segment is being set to '✗' with the color 'bold red'

[cmd_duration]
show_milliseconds = true

[direnv]
disabled = false
symbol = 'direnv '
allowed_msg = '✅'
not_allowed_msg = '❌'
denied_msg = '🚫'
loaded_msg = '🟢'
unloaded_msg = '⚪'
