# Preload images (optional but recommended for faster switching)
preload = ~/.dotfiles/wallpapers/Control/33.jpg
preload = ~/.dotfiles/wallpapers/Control/41.jpg

# Wallpaper settings
wallpaper {
    monitor   = DP-1
    path      = ~/.dotfiles/wallpapers/Control/33.jpg
    fit_mode  = contain
}

wallpaper {
    monitor   = DP-2
    path      = ~/.dotfiles/wallpapers/Control/41.jpg
    fit_mode  = contain
}

